       
################################################################################
# Define Test Matrix
matrix:
    include:      
        - php: 7.2
        - php: 7.3
        - php: 7.4

################################################################################
# TEST SCRIPTS
################################################################################

################################################################################
# Prepare Test Environnement
before_install:

################################################################################
# Install & Configure Environnement
install:
    # Setup Travis
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh  | sh
    # Deploy Symfony Files
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
    # Setup Symfony Version & Create Database
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
    # Install Symfony
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh

################################################################################
# Run Test Script
script:
    # Execute Grumphp Testsuite
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh  | sh
    # Show Basic Command Results
    - php bin/splash
    - php bin/console splash:server:config
    - php bin/console splash:objects:types

################################################################################
# Run After Script
after_script:
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/after.sh | sh

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always