       
################################################################################
# Define Test Matrix
matrix:
    include:      
        - php: 7.1
        - php: 7.2
        - php: 7.3
        
    allow_failures:
        - php: 7.3
        
    fast_finish: true

################################################################################
# Prepare Test Environement
before_install:

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Install composer dependencies,
# Create database, schema and fixtures
install:   
#    # Setup MailChimp Connector
    - sed -i -e 's/ThisIsSecretApiKey/'$SIB_API_KEY'/g' tests/config/splash.yml >/dev/null 2>&1
    - sed -i -e 's/ThisIsSecretApiList/'$SIB_API_LIST'/g' tests/config/splash.yml >/dev/null 2>&1

    # Setup Travis
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/configure.sh  | bash
    # Configure For Phpstan vs PHP Versions
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_grumphp.sh  | bash
    # Composer Build
    - echo "Build Dependencies"
    - composer update  --prefer-dist --no-interaction  

################################################################################
# Run script
script:
    # Execute Grump Travis Testsuite 
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP > 7.0 => Execute CsFixer
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=csfixer; fi    
    # With PHP > 7.0 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=phpstan; fi   
    # Show Basic Command Results   
    - php bin/splash
    - php bin/splash config
    # Show Outdated Packages   
    - composer outdated
    

################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always