       
################################################################################
# Define Test Matrix
matrix:
    include:      
        - php: 7.1
        - php: 7.2
        - php: 7.3
        
    fast_finish: true

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Prepare Test Environement
before_install:
    - echo "Configuring The Bundles"
    - cp tests/config/parameters.yml.dist tests/config/parameters.yml
    - echo "Configuring Folders"
    - cp tests/console bin/console
    - mkdir public
    - cp tests/public/* public
    - cp tests/public/.htaccess public/.htaccess
    
################################################################################
# Install composer dependencies,
# Create database, schema and fixtures
install:
    # With PHP < 7.3 => Rollback to Composer 1
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.3" ]]; then composer self-update --rollback; fi
    # Setup Travis
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/configure.sh  | bash
    # Setup Symfony Version if Required
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_symfony.sh  | bash
    # Configure For Phpstan vs PHP Versions
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_grumphp.sh  | bash
    # Composer Build
    - echo "Build Dependencies"
    - composer update  --prefer-dist --no-interaction  
    
################################################################################
# Run script
script:
    # Execute Grump Travis Testsuite 
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP > 7.0 => Execute CsFixer
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=csfixer; fi    
    # With PHP > 7.0 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=phpstan; fi   
#    # Install Symfony
#    - echo "Install Symfony"
#    - php bin/console doctrine:schema:update --force  --no-interaction --no-debug    
    # Show Basic Command Results   
    - php bin/splash
    - php bin/console splash:server:config
    - php bin/console splash:objects:types
    # Show Outdated Packages   
    - composer outdated
    

################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always