################################################################################
#
# * This file is part of SplashSync Project.
# *
# * Copyright (C) Splash Sync <www.splashsync.com>
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# *
# * For the full copyright and license information, please view the LICENSE
# * file that was distributed with this source code.
# *
# * @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Base Settings fro All Sites
title: Splash Docs
subtitle: Template
repository: SplashSync/Php-Console
email: contact@splashsync.com
github_username:  splashsync
url: "splashsync.github.io"
home-logo:
    splash:     true
    
################################################################################
# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-sass-converter
    - jekyll-polyglot
    - jekyll-github-metadata    
    - jekyll-feed

################################################################################
# Configure Polyglot Plugin    
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
data_dir: _data

################################################################################
# Core Translations    
langs:
  en: English
  fr: Français

################################################################################
# Blog Permalinks
permalink: /:categories/:year/:title:output_ext

################################################################################
# Assets
sass:
    style: compressed
    
################################################################################
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
